### ISSUE TITLE
添加使用vault内相对作为书库的选项

### ISSUE THREAD

**Issue by YQGong** [chenghongyao/obsidian-bookmaster-plugin#6]
目前我使用了第三方的文件同步工具，并且在每个电脑上都会用符号链接将zotero的文件链接到obsidian的attachments文件夹中，也就是说具有相同的局部地址，但是全局地址无法做到每台电脑都相同。
因此目前的绝对路径方式无法实现mac windows多端同步。
增加一个开关来选择使用相对路径或绝对路径，就可以解决上述问题。

**Comment by chenghongyao** [comment]
1.将ob库本身作为一个特殊的书库在计划中，应该不会支持使用库内的相对路径。
2.书库路径的多设备支持也在计划中，目前的建议是不要同步data.json文件，不同设备使用不同的设置文件。

**Comment by chenghongyao** [comment]
最新版已经支持多设备，也增加了内部笔记库文件支持，请使用最新版本测试，还有问题可以重新打开issue。
